theme: jekyll-theme-minimal
title: Strata Scratch Educational Guides & Exercises
description: Whether you're a student looking to supercharge your data analysis skills or a teacher looking to power 
your classroom, we've included a few guides and exercises to help you along your analytical journey. Our guides and exercises are listed on this page but can also be accessed on our [GitHub](https://github.com/stratascratch). We encourage you to share any or all your data analyses performed on our public datasets. Post your analyses on our [community-contribution](https://github.com/stratascratch/community-contributions) repository.
google_analytics: UA-115949776-1
