theme: jekyll-theme-minimal
title: Strata Scratch Problem Sets
description: Problem sets, exercises, and educational guides for SQL and python. These exercises are specifically tailored for business and marketing analytics students and novices.
google_analytics:
